#!/bin/bash

echo "🖥️ SCREEN SHARING TROUBLESHOOTING GUIDE"
echo "======================================"
echo ""

echo "🔍 STEP 1: Test Browser Screen Sharing"
echo "---------------------------------------"
echo "1. Open http://localhost:3000 in your browser"
echo "2. Press F12 to open developer console"
echo "3. Copy and paste this script into console:"
echo ""
echo "fetch('/Volumes/Development/livekit/livekit-agent/livekit_screen_debug.js')"
echo "  .then(r => r.text())"
echo "  .then(code => eval(code));"
echo ""

echo "🔍 STEP 2: Check Console Errors"
echo "------------------------------"
echo "Look for these specific errors:"
echo "• NotAllowedError: Permission denied"
echo "• NotReadableError: Source already in use"
echo "• Permission denied: canPublish = false"
echo ""

echo "🔍 STEP 3: Verify Browser Settings"
echo "---------------------------------"
echo "Chrome: chrome://settings/content/screenshare"
echo "Firefox: about:preferences#privacy"
echo "Safari: Safari > Preferences > Websites > Screen Sharing"
echo ""

echo "🔍 STEP 4: Common Issues & Solutions"
echo "------------------------------------"
echo ""
echo "❌ 'Permission denied':"
echo "   • Click 'Allow' when browser prompts"
echo "   • Check browser screen sharing settings"
echo "   • Try refreshing the page"
echo ""
echo "❌ 'Source already in use':"
echo "   • Close other screen sharing apps"
echo "   • Restart browser"
echo "   • Try sharing a different window/tab"
echo ""
echo "❌ 'No screen share tracks found':"
echo "   • This means permission was granted but track failed"
echo "   • Check if agent can receive screen tracks"
echo "   • May need to restart the session"
echo ""

echo "🔍 STEP 5: Test with Different Content"
echo "--------------------------------------"
echo "Try sharing different things:"
echo "• Entire screen"
echo "• Application window"
echo "• Browser tab"
echo "• Different browser window"
echo ""

echo "🔧 DEBUG INFO:"
echo "-------------"
echo "Agent is running in: LiveKit Cloud (dev mode)"
echo "Frontend URL: http://localhost:3000"
echo "Room: security-plus-room"
echo "Permissions: canPublish = true ✅"
echo ""

echo "📞 If still not working:"
echo "• Run the debug script above"
echo "• Check browser console for specific errors"
echo "• Try a different browser (Chrome recommended)"
echo ""

echo "🎯 Start with Step 1 and follow the debugging output!"
